name: Run ICS Sync

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests ics

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_JADA_TOKEN }}
        run: python airbnb_sync.py
